SELECT * FROM USUARIO;

SELECT * FROM PACIENTE;
SELECT * FROM SALUD;
SELECT * FROM TIPO_SALUD;
SELECT * FROM MEDICO;
SELECT COMISION FROM MEDICO;
SELECT * FROM ESPECIALIDAD;
SELECT * FROM UNIDAD;
SELECT * FROM ATENCION;
SELECT * FROM PAGO_ATENCION;

CREATE OR REPLACE PROCEDURE SP_LOGIN_USUARIO(P_USER VARCHAR2,P_PASS VARCHAR2,P_USUARIO OUT NUMBER)
IS
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE FROM USUARIO WHERE USUARIO = P_USER AND PASS=P_PASS;
    IF V_EXISTE>0 THEN
        P_USUARIO:=1;
    ELSE
        P_USUARIO:=0;
    END IF;
END SP_LOGIN_USUARIO;

--CRUD PACIENTE
CREATE OR REPLACE PROCEDURE SP_GUARDAR_PACIENTE(P_RUT IN NUMBER,P_DV_RUT VARCHAR2, P_NOMBRE VARCHAR2,
    P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2,P_AMATERNO VARCHAR2,P_FECNACIMIENTO DATE,P_TELEFONO NUMBER,P_SALUD VARCHAR2,P_RETORNO OUT NUMBER)
IS
    V_IDSALUD NUMBER;
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_EXISTE FROM PACIENTE WHERE PAC_RUT=P_RUT;
    IF V_EXISTE=1 THEN
        P_RETORNO:=0;
    ELSE
        SELECT SAL_ID INTO V_IDSALUD FROM SALUD WHERE DESCRIPCION=P_SALUD;
        INSERT INTO PACIENTE VALUES(P_RUT,P_DV_RUT, P_NOMBRE,P_SNOMBRE,P_APATERNO,P_AMATERNO,P_FECNACIMIENTO,P_TELEFONO,V_IDSALUD);
        P_RETORNO:=1;
    END IF;
END SP_GUARDAR_PACIENTE;

CREATE OR REPLACE PROCEDURE SP_MODIFICAR_PACIENTE(P_RUT NUMBER,P_DV_RUT VARCHAR2, P_NOMBRE VARCHAR2,
    P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2,P_AMATERNO VARCHAR2,P_FECNACIMIENTO DATE,P_TELEFONO NUMBER,P_SALUD VARCHAR2)
IS
    v_IDSALUD NUMBER;
BEGIN
    SELECT SAL_ID INTO V_IDSALUD FROM SALUD WHERE DESCRIPCION=P_SALUD;
    UPDATE PACIENTE SET PNOMBRE=P_NOMBRE,SNOMBRE=P_SNOMBRE,APATERNO=P_APATERNO,AMATERNO=P_AMATERNO,
    FECHA_NACIMIENTO=P_FECNACIMIENTO,TELEFONO=P_TELEFONO,SAL_ID=V_IDSALUD WHERE PAC_RUT=P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_LISTAR_PACIENTES(P_PACIENTE OUT SYS_REFCURSOR)
IS
BEGIN
    /*OPEN P_PACIENTE
    FOR
        SELECT * FROM PACIENTE;*/
    OPEN P_PACIENTE
    FOR
        SELECT pa.PAC_RUT,pa.DV_RUT,pa.PNOMBRE,pa.SNOMBRE,pa.APATERNO,pa.AMATERNO,pa.FECHA_NACIMIENTO, pa.TELEFONO, sa.descripcion FROM PACIENTE pa
        INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_PACIENTE(P_RUT NUMBER, P_PACIENTE OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_PACIENTE FOR
        SELECT pa.PAC_RUT,pa.DV_RUT,pa.PNOMBRE,pa.SNOMBRE,pa.APATERNO,pa.AMATERNO,pa.FECHA_NACIMIENTO, pa.TELEFONO, sa.descripcion FROM PACIENTE pa
        INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id WHERE pa.PAC_RUT = P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PACIENTE(P_RUT NUMBER)
IS
    V_IDATENCION NUMBER;
BEGIN
    --SELECT ATE_ID INTO V_IDATENCION FROM ATENCION WHERE pac_rut=P_RUT;
    DELETE FROM PAGO_ATENCION WHERE ATE_ID IN (SELECT ATE_ID FROM ATENCION WHERE PAC_RUT = P_RUT);
    DELETE FROM ATENCION WHERE pac_rut=P_RUT;
    DELETE FROM PACIENTE WHERE PAC_RUT = P_RUT;
END;


CREATE OR REPLACE PROCEDURE SP_OBTENER_SALUD_SPINNER(P_SALUD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_SALUD 
    FOR
        SELECT DESCRIPCION FROM SALUD;
END;


--PROCEDIMIENTOS ATENCIÓN
CREATE OR REPLACE PROCEDURE SP_LISTAR_ATENCIONES(P_ATENCION OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ATENCION FOR
        SELECT ate.ATE_ID,me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
                pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT PACIENTE",pa.PNOMBRE||' '||pa.APATERNO AS "NOMBRE PACIENTE",
                ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION" FROM ATENCION ate
                INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
                INNER JOIN MEDICO me ON ate.med_rut=me.med_rut;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_ATENCION(P_RUT NUMBER,P_ATENCION OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ATENCION FOR
        SELECT ate.ATE_ID,me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
                pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT PACIENTE",pa.PNOMBRE||' '||pa.APATERNO AS "NOMBRE PACIENTE",
                ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION" FROM ATENCION ate
                INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
                INNER JOIN MEDICO me ON ate.med_rut=me.med_rut
                WHERE me.med_rut=P_RUT OR pa.pac_rut=P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_GUARDAR_ATENCION(P_COSTO NUMBER, P_MED_RUT NUMBER, P_PAC_RUT NUMBER, P_FEC_VENC_PAGO DATE)
IS
    V_IDATENCION NUMBER;
    V_COSTO_SALUD NUMBER(3);
    V_COSTO_ATENCION NUMBER;
    V_MONTO_PAGAR NUMBER;
    V_EDAD NUMBER;
    V_PORC_DESCTO NUMBER;
BEGIN
    V_IDATENCION:=SEQ_ATENCION.NEXTVAL;
    INSERT INTO ATENCION VALUES(V_IDATENCION,SYSDATE,TO_CHAR(SYSDATE,'HH24:MM'),P_COSTO,P_MED_RUT,P_PAC_RUT);
    --P_IDATENCION:=V_IDATENCION;
    
    --OBTENER COSTO DE SALUD
    SELECT sa.COSTO_PAGO INTO V_COSTO_SALUD FROM PACIENTE pa
    JOIN SALUD sa
    ON pa.SAL_ID = sa.SAL_ID
    WHERE pa.PAC_RUT=P_PAC_RUT;
    
    --OBTENER COSTO DE ATENCION
    SELECT COSTO INTO V_COSTO_ATENCION FROM ATENCION WHERE ate_id=V_IDATENCION;

    --OBTENER EDAD
    SELECT 
        trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(fecha_nacimiento, 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) INTO V_EDAD
    FROM PACIENTE WHERE PAC_RUT=P_PAC_RUT;
    
    --OBTENER PORC DESCTO
    IF V_EDAD>=65 AND V_EDAD<=120 THEN
        SP_OBTENER_DESCUENTO_3RA_EDAD(V_EDAD, V_PORC_DESCTO);
    ELSE
        V_PORC_DESCTO:=0;
    END IF;
    
    --CALCULAR MONTO A CANCELAR
    V_MONTO_PAGAR:=(V_COSTO_SALUD+V_COSTO_ATENCION)+((V_COSTO_SALUD+V_COSTO_ATENCION)*V_PORC_DESCTO);
    
    --INGRESAR PAGO ATENCION
    INSERT INTO PAGO_ATENCION VALUES(V_IDATENCION,P_FEC_VENC_PAGO,NULL, V_COSTO_ATENCION,V_MONTO_PAGAR,NULL);
END;

/*
CREATE OR REPLACE TRIGGER TRG_INSERTAR_PAGO_ATENCION
	AFTER INSERT ON PAGO_ATENCION FOR EACH ROW
DECLARE
    V_PAC_RUT NUMBER;
    V_COSTO NUMBER;
    V_COSTO_SALUD NUMBER;
    V_MONTO_CANCELAR NUMBER;
    V_PORC_DESCTO NUMBER;
    V_EDAD NUMBER;
BEGIN
    --Verificar si posee pago
    SELECT PAC_RUT INTO V_PAC_RUT FROM ATENCION WHERE ATE_ID=:NEW.ATE_ID;
    
    SELECT COSTO INTO V_COSTO FROM ATENCION WHERE ATE_ID=:NEW.ATE_ID;
    
    SELECT sa.COSTO_PAGO INTO V_COSTO_SALUD FROM PACIENTE pa
    JOIN SALUD sa
    ON pa.SAL_ID = sa.SAL_ID
    WHERE pa.PAC_RUT=V_PAC_RUT;
        
    SELECT 
        trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(fecha_nacimiento, 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) INTO V_EDAD
    FROM PACIENTE WHERE PAC_RUT=V_PAC_RUT;
    
    IF V_EDAD>=65 AND V_EDAD<=120 THEN
        SP_OBTENER_DESCUENTO_3RA_EDAD(V_EDAD, V_PORC_DESCTO);
    ELSE
        V_PORC_DESCTO:=0;
    END IF;
    
    V_MONTO_CANCELAR:=(V_COSTO_SALUD+V_COSTO)+((V_COSTO_SALUD+V_COSTO)*V_PORC_DESCTO);  
    
	UPDATE PAGO_ATENCION SET MONTO_A_CANCELAR=V_MONTO_CANCELAR WHERE ATE_ID=:NEW.ATE_ID;
    
END TRG_INSERTAR_PAGO_ATENCION;
*/
CREATE OR REPLACE PROCEDURE SP_OBTENER_PAGO(P_IDATENCION NUMBER, P_PAGO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_PAGO FOR
        SELECT ate.ate_id,ate.COSTO, TO_CHAR(pa.fecha_venc_pago,'DD-MM-YYYY') AS "FECHA_VENCIMIENTO", pa.monto_a_cancelar,nvl(OBS_PAGO, '') AS "OBSERVACION_PAGO" FROM ATENCION ate
        INNER JOIN PAGO_ATENCION pa ON pa.ate_id=ate.ate_id
        WHERE ate.ate_id=P_IDATENCION;
END;

CREATE OR REPLACE PROCEDURE SP_GUARDAR_PAGO_ATENCION(P_IDATENCION NUMBER, P_OBS VARCHAR2)
IS
BEGIN
    UPDATE PAGO_ATENCION SET FECHA_PAGO=SYSDATE, OBS_PAGO=P_OBS WHERE ATE_ID = P_IDATENCION;
END;

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_ATENCION(P_IDATENCION NUMBER)
IS
BEGIN
    DELETE FROM PAGO_ATENCION WHERE ATE_ID=P_IDATENCION;
    DELETE FROM ATENCION WHERE ATE_ID=P_IDATENCION;
END;

CREATE OR REPLACE PROCEDURE ACTUALIZAR_MONTO_ATENCION
IS
    V_COSTO_SALUD NUMBER;
    V_COSTO_ATENCION NUMBER;
    V_EDAD NUMBER;
    V_PORC_DESCTO NUMBER;
    V_MONTO_PAGAR NUMBER;
BEGIN
    FOR p IN (SELECT pag.ate_id,pac.pac_rut,ate.costo,sa.costo_pago FROM PAGO_ATENCION pag
                INNER JOIN ATENCION ate ON ate.ate_id=pag.ate_id
                INNER JOIN PACIENTE pac ON pac.pac_rut = ate.pac_rut
                INNER JOIN SALUD sa ON pac.sal_id=sa.sal_id)
        LOOP
            V_COSTO_SALUD:=p.COSTO_PAGO;
            V_COSTO_ATENCION:=p.COSTO;
            SELECT 
                trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(fecha_nacimiento, 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) INTO V_EDAD
            FROM PACIENTE WHERE PAC_RUT=p.PAC_RUT;

            --OBTENER PORC DESCTO
            IF V_EDAD>=65 AND V_EDAD<=120 THEN
                SP_OBTENER_DESCUENTO_3RA_EDAD(V_EDAD, V_PORC_DESCTO);
            ELSE
                V_PORC_DESCTO:=0;
            END IF;

            --CALCULAR MONTO A CANCELAR
            V_MONTO_PAGAR:=(V_COSTO_SALUD+V_COSTO_ATENCION)+((V_COSTO_SALUD+V_COSTO_ATENCION)*V_PORC_DESCTO);
            UPDATE PAGO_ATENCION SET MONTO_A_CANCELAR=V_MONTO_PAGAR,OBS_PAGO='NINGUNA' WHERE ATE_ID=p.ATE_ID;
        END LOOP;
END;

SELECT nvl(OBS_PAGO, 'NINGUNA') AS "OBSERVACION_PAGO" FROM PAGO_ATENCION;


--PROCEDIMIENTOS ADMINISTRADOR MEDICO
CREATE OR REPLACE PROCEDURE SP_GUARDAR_MEDICO(P_RUT NUMBER, P_DV_RUT VARCHAR2,P_NOMBRE VARCHAR2, P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2, P_AMATERNO VARCHAR2,
                        P_TELEFONO NUMBER, P_SUELDO_BASE NUMBER, P_FECHA_CONTRATO DATE, P_COMISION NUMBER, P_UNIDAD VARCHAR2, 
                        P_CARGO VARCHAR2, P_ESP VARCHAR2, P_JEFE_RUT NUMBER, P_RETORNO OUT NUMBER)
IS
    V_JEFE NUMBER;
    V_UNIDAD_ID NUMBER;
    V_CARGO_ID NUMBER;
    V_ESP_ID NUMBER;
    V_EXISTE NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_JEFE FROM MEDICO WHERE jefe_rut = P_JEFE_RUT;
    SELECT COUNT(*) INTO V_EXISTE FROM MEDICO WHERE MED_RUT=P_RUT;
    IF V_JEFE = 0 THEN
        P_RETORNO:=0;
    ELSIF V_EXISTE=1 THEN
        P_RETORNO:=3;
    ELSE
        SELECT UNI_ID INTO V_UNIDAD_ID FROM UNIDAD WHERE NOMBRE=P_UNIDAD;
        SELECT CAR_ID INTO V_CARGO_ID FROM CARGO WHERE NOMBRE=P_CARGO;
        SELECT ESP_ID INTO V_ESP_ID FROM ESPECIALIDAD WHERE NOMBRE=P_ESP;
        INSERT INTO MEDICO VALUES(P_RUT,P_DV_RUT,P_NOMBRE,P_SNOMBRE,P_APATERNO,P_AMATERNO,P_TELEFONO,P_SUELDO_BASE,P_FECHA_CONTRATO,P_COMISION,V_UNIDAD_ID,V_CARGO_ID,V_ESP_ID,P_JEFE_RUT);
        P_RETORNO:=1;
    END IF;
END;

CREATE OR REPLACE PROCEDURE SP_MODIFICAR_MEDICO(P_RUT NUMBER,P_NOMBRE VARCHAR2, P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2, P_AMATERNO VARCHAR2,
                        P_TELEFONO NUMBER, P_SUELDO_BASE NUMBER, P_FECHA_CONTRATO DATE, P_COMISION NUMBER, P_UNIDAD VARCHAR2, 
                        P_CARGO VARCHAR2, P_ESP VARCHAR2, P_JEFE_RUT NUMBER,P_RETORNO OUT NUMBER)
IS
    V_JEFE NUMBER;
    V_UNIDAD_ID NUMBER;
    V_CARGO_ID NUMBER;
    V_ESP_ID NUMBER;
BEGIN
    SELECT COUNT(*) INTO V_JEFE FROM MEDICO WHERE JEFE_RUT = P_JEFE_RUT;
    IF V_JEFE = 0 THEN
        P_RETORNO:=0;
    ELSE
        SELECT UNI_ID INTO V_UNIDAD_ID FROM UNIDAD WHERE NOMBRE=P_UNIDAD;
        SELECT CAR_ID INTO V_CARGO_ID FROM CARGO WHERE NOMBRE=P_CARGO;
        SELECT ESP_ID INTO V_ESP_ID FROM ESPECIALIDAD WHERE NOMBRE=P_ESP;
        UPDATE MEDICO SET PNOMBRE=P_NOMBRE,SNOMBRE=P_SNOMBRE,APATERNO=P_APATERNO,AMATERNO=P_AMATERNO,TELEFONO=P_TELEFONO,
        SUELDO_BASE=P_SUELDO_BASE,FECHA_CONTRATO=P_FECHA_CONTRATO,COMISION=P_COMISION,UNI_ID=V_UNIDAD_ID,CAR_ID=V_CARGO_ID,ESP_ID=V_ESP_ID,JEFE_RUT=P_JEFE_RUT WHERE MED_RUT=P_RUT;
        P_RETORNO:=1;
    END IF;
END;

CREATE OR REPLACE PROCEDURE SP_LISTAR_MEDICOS(P_MEDICO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_MEDICO FOR
        SELECT me.MED_RUT,me.DV_RUT,me.PNOMBRE,me.SNOMBRE,me.APATERNO,me.AMATERNO,me.TELEFONO,me.SUELDO_BASE,me.FECHA_CONTRATO,NVL(me.COMISION,0) AS "COMISION",
        u.NOMBRE AS "UNIDAD",ca.NOMBRE AS "CARGO",es.NOMBRE AS "ESPECIALIDAD",NVL(me.JEFE_RUT,0) AS "JEFE_RUT" FROM MEDICO me
        JOIN UNIDAD u ON u.uni_id=me.uni_id
        JOIN CARGO ca ON ca.car_id=me.car_id
        JOIN ESPECIALIDAD es ON es.esp_id=me.esp_id;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_MEDICO(P_RUT NUMBER, P_MEDICO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_MEDICO FOR
        SELECT me.MED_RUT,me.DV_RUT,me.PNOMBRE,me.SNOMBRE,me.APATERNO,me.AMATERNO,me.TELEFONO,me.SUELDO_BASE,me.FECHA_CONTRATO,NVL(me.COMISION,0) AS "COMISION",
        u.NOMBRE AS "UNIDAD",ca.NOMBRE AS "CARGO",es.NOMBRE AS "ESPECIALIDAD",NVL(me.JEFE_RUT,0) AS "JEFE_RUT" FROM MEDICO me
        JOIN UNIDAD u ON u.uni_id=me.uni_id
        JOIN CARGO ca ON ca.car_id=me.car_id
        JOIN ESPECIALIDAD es ON es.esp_id=me.esp_id
        WHERE me.MED_RUT = P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_MEDICO(P_RUT NUMBER)
IS
    V_IDATENCION NUMBER;
BEGIN
    --SELECT ATE_ID INTO V_IDATENCION FROM ATENCION WHERE med_rut=P_RUT;
    DELETE FROM PAGO_ATENCION WHERE ATE_ID IN (SELECT ATE_ID FROM ATENCION WHERE MED_RUT = P_RUT);
    DELETE FROM ATENCION WHERE med_rut=P_RUT;
    DELETE FROM MEDICO WHERE MED_RUT = P_RUT;
END;

SELECT * FROM UNIDAD;

CREATE OR REPLACE PROCEDURE SP_OBTENER_DESCUENTO_3RA_EDAD(P_EDAD NUMBER, P_PORC_DESCTO OUT NUMBER)
IS
    V_PORC_DESC NUMBER;
BEGIN
    SELECT PORCENTAJE_DESCTO INTO V_PORC_DESC FROM PORC_DESCTO_3RA_EDAD WHERE ANNO_INI<=P_EDAD AND ANNO_TER>=P_EDAD;
    P_PORC_DESCTO:=V_PORC_DESC;
END;


CREATE OR REPLACE PROCEDURE SP_SPINNER_ESP(P_ESPECIALIDAD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ESPECIALIDAD
    FOR
        SELECT NOMBRE FROM ESPECIALIDAD;
END;

CREATE OR REPLACE PROCEDURE SP_SPINNER_UNI(P_UNIDAD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_UNIDAD
    FOR
        SELECT NOMBRE FROM UNIDAD;
END;

CREATE OR REPLACE PROCEDURE SP_SPINNER_CAR(P_CARGO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_CARGO
    FOR
        SELECT NOMBRE FROM CARGO;
END;

SELECT * FROM MEDICO;

/*
CREATE OR REPLACE PROCEDURE SP_LISTAR_ATENCIONES_PACIENTE(P_RUT_PAC NUMBER,P_ATENCION OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ATENCION FOR
        SELECT ate.ATE_ID,me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
                pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT PACIENTE",pa.PNOMBRE||' '||pa.APATERNO AS "NOMBRE PACIENTE",
                ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
                INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
                INNER JOIN MEDICO me ON ate.med_rut=me.med_rut
                WHERE pa.PAC_RUT=P_RUT_PAC;
END;

CREATE OR REPLACE PROCEDURE SP_LISTAR_ATENCIONES_MEDICO(P_RUT_MED NUMBER,P_ATENCION_MEDICO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ATENCION_MEDICO FOR
        SELECT ate.ATE_ID,me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
                pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT PACIENTE",pa.PNOMBRE||' '||pa.APATERNO AS "NOMBRE PACIENTE",
                ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
                INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
                INNER JOIN MEDICO me ON ate.med_rut=me.med_rut
                WHERE me.med_rut=P_RUT_MED;
END;
*/

--No es Necesario
/*
CREATE OR REPLACE PROCEDURE SP_OBTENER_SALUD(P_SALUD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_SALUD
    FOR
        SELECT sa.SAL_ID, sa.COSTO_PAGO, sa.DESCRIPCION, sa.COSTO_PAGO, sa.TIPO_SAL_ID FROM SALUD sa;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_TIPO_SALUD(P_TIPO_SALUD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_TIPO_SALUD
    FOR
        SELECT TIPO_SAL_ID, DESCRIPCION FROM TIPO_SALUD;
END;
*/

--NO EJECUTAR
SELECT * FROM ATENCION ate;
SELECT * FROM PAGO_ATENCION;

SELECT ate.ATE_ID,pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE",ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
        INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut;

SELECT COUNT(*) FROM MEDICO WHERE JEFE_RUT = 3490261;

SELECT ate.ATE_ID,pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE",ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
    INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut;

SELECT * FROM MEDICO;
SELECT * FROM ATENCION;
SELECT * FROM PAGO_ATENCION;

DECLARE 
    C_PACIENTE SYS_REFCURSOR;
    V_RUT NUMBER;
BEGIN
    LISTAR_RUT_PACIENTES(C_PACIENTE);
    LOOP 
        FETCH C_PACIENTE INTO V_RUT;
        EXIT WHEN C_PACIENTE%NOTFOUND;
        dbms_output.put_line(V_RUT);
    END LOOP;
    CLOSE C_PACIENTE;
END;

--CALCULAR EDAD DEL PACIENTE
SELECT 
    trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(fecha_nacimiento, 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) AS "EDAD"
FROM PACIENTE;

SELECT * FROM MEDICO;
SELECT * FROM USUARIO;
SELECT * FROM ATENCION;
SELECT * FROM PACIENTE;
SELECT * FROM SALUD;
SELECT * FROM TIPO_SALUD;
SELECT pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE", sa.descripcion FROM PACIENTE pa
INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id;
SELECT * FROM PORC_DESCTO_3RA_EDAD;

SELECT * FROM ATENCION;
SELECT TO_CHAR(SYSDATE,'HH24:MM') AS CURRENT_HOUR FROM DUAL;

--PREGUNTAR ACERCA DE LA TABLA ATENCIONES_MEDICAS_MENSUALES
--MONTO A ATENCION DE LA TABLA PAGO ATENCION
--COSTO DE LA TABLA ATENCION
--COSTO PAGO SALUD

--INSERT INTO VALUES(,,) RETURNING ID INTO V_ID;
--UPDATE
--DELETE

--******************************************NO UTILIZAR************************************
CREATE OR REPLACE PROCEDURE INGRESAR_USUARIO(P_USUARIO VARCHAR2, P_PASS VARCHAR2, P_IDTIPOUSUARIO NUMBER, P_IDUSUARIO OUT NUMBER)
IS
    V_IDUSUARIO NUMBER;
BEGIN
    V_IDUSUARIO:=SEQ_USUARIO.NEXTVAL;
    INSERT INTO USUARIO VALUES (V_IDUSUARIO,P_USUARIO,P_PASS,P_IDTIPOUSUARIO);
    P_IDUSUARIO:=V_IDUSUARIO;
END INGRESAR_USUARIO;