SELECT * FROM PACIENTE;

CREATE OR REPLACE PROCEDURE SP_LOGIN_USUARIO(P_USER VARCHAR2,P_PASS VARCHAR2,P_USUARIO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_USUARIO
    FOR
       SELECT * FROM USUARIO WHERE USUARIO = P_USER AND PASS=P_PASS;
END SP_LOGIN_USUARIO;

--CRUD PACIENTE
CREATE OR REPLACE PROCEDURE SP_GUARDAR_PACIENTE(P_RUT IN OUT NUMBER,P_DV_RUT VARCHAR2, P_NOMBRE VARCHAR2,
    P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2,P_AMATERNO VARCHAR2,P_FECNACIMIENTO DATE,P_TELEFONO VARCHAR2,P_SALUD_ID NUMBER)
IS
BEGIN
    INSERT INTO PACIENTE VALUES(P_RUT,P_DV_RUT, P_NOMBRE,P_SNOMBRE,P_APATERNO,P_AMATERNO,P_FECNACIMIENTO,P_TELEFONO,P_SALUD_ID);
END SP_INGRESAR_PACIENTE;

CREATE OR REPLACE PROCEDURE SP_MODIFICAR_PACIENTE(P_RUT IN OUT NUMBER,P_DV_RUT VARCHAR2, P_NOMBRE VARCHAR2,
    P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2,P_AMATERNO VARCHAR2,P_FECNACIMIENTO DATE,P_TELEFONO VARCHAR2,P_SALUD_ID NUMBER)
IS
BEGIN
    UPDATE PACIENTE SET PNOMBRE=P_NOMBRE,SNOMBRE=P_SNOMBRE,APATERNO=P_APATERNO,AMATERNO=P_AMATERNO,
    FECHA_NACIMIENTO=P_FECNACIMIENTO,TELEFONO=P_TELEFONO,SAL_ID=P_SALUD_ID WHERE PAC_RUT=P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_LISTAR_PACIENTES(P_PACIENTE OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_PACIENTE
    FOR
        SELECT * FROM PACIENTE;
    /*OPEN P_PACIENTE
    FOR
        SELECT pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE",TO_CHAR(pa.FECHA_NACIMIENTO,'DD/MM/YYYY') AS "FECHA_NACIMIENTO", pa.TELEFONO, sa.descripcion FROM PACIENTE pa
        INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id;*/
END;

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PACIENTE(P_RUT NUMBER)
IS
BEGIN
    DELETE FROM PACIENTE WHERE PAC_RUT = P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_SALUD(P_SALUD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_SALUD
    FOR
        SELECT sa.SAL_ID, sa.COSTO, sa.DESCRIPCION, sa.COSTO_PAGO, sa.TIPO_SAL_ID FROM SALUD sa;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_TIPO_SALUD(P_TIPO_SALUD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_TIPO_SALUD
    FOR
        SELECT TIPO_SAL_ID, DESCRIPCION FROM TIPO_SALUD;
END;

--PROCEDIMIENTOS  ADMINISTRADOR PACIENTES

CREATE OR REPLACE PROCEDURE SP_GUARDAR_ATENCION_MED(P_COSTO NUMBER, P_MED_RUT NUMBER, P_PAC_RUT NUMBER, P_FEC_VENC_PAGO DATE,P_IDATENCION OUT NUMBER)
IS
    V_IDATENCION NUMBER;
    V_COSTO_SALUD NUMBER(3);
    V_COSTO_ATENCION NUMBER;
    V_MONTO_PAGAR NUMBER;
BEGIN
    V_IDATENCION:=SEQ_ATENCION.NEXTVAL;
    INSERT INTO ATENCION VALUES(V_IDATENCION,SYSDATE,TO_CHAR(SYSDATE,'HH24:MM'),P_COSTO,P_MED_RUT,P_PAC_RUT);
    P_IDATENCION:=V_IDATENCION;
    
    --OBTENER COSTO DE SALUD
    SELECT sa.COSTO_PAGO INTO V_COSTO_SALUD FROM PACIENTE pa
    JOIN SALUD sa
    ON pa.SAL_ID = sa.SAL_ID
    WHERE pa.PAC_RUT=P_PAC_RUT;
    
    --OBTENER COSTO DE ATENCION
    SELECT COSTO INTO V_COSTO_ATENCION FROM ATENCION WHERE ate_id=V_IDATENCION;
    V_MONTO_PAGAR:=V_COSTO_SALUD+V_COSTO_ATENCION;
    
    --INGRESAR PAGO ATENCION
    INSERT INTO PAGO_ATENCION VALUES(V_IDATENCION,P_FEC_VENC_PAGO,NULL, V_COSTO_ATENCION,V_MONTO_PAGAR,NULL);
END;

CREATE OR REPLACE PROCEDURE SP_GUARDAR_PAGO_ATENCION(P_IDATENCION NUMBER, P_OBS VARCHAR2)
IS
BEGIN
    UPDATE PAGO_ATENCION SET FECHA_PAGO=SYSDATE, OBS_PAGO=P_OBS;
END;



--PROCEDIMIENTOS ADMINISTRADOR MEDICO
CREATE OR REPLACE PROCEDURE SP_GUARDAR_MEDICO(P_RUT NUMBER, P_DV_RUT VARCHAR2,P_NOMBRE VARCHAR2(, P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2, P_AMATERNO VARCHAR2,
                        P_TELEFONO NUMBER, P_SUELDO_BASE NUMBER, P_FECHA_CONTRATO DATE, P_COMISION NUMBER, P_UNI_ID NUMBER, 
                        P_CARGO_ID NUMBER, P_ESP_ID NUMBER, P_JEFE_RUT NUMBER
IS
BEGIN
    INSERT INTO MEDICO VALUES(P_RUT,P_DV_RUT,P_NOMBRE,P_SNOMBRE,P_APATERNO,P_AMATERNO,P_TELEFONO,P_SUELDO_BASE,P_FECHA_CONTRATO,P_COMISION,P_UNI_ID,P_CARGO_ID,P_ESP_ID,P_JEFE_RUT);
END;

CREATE OR REPLACE PROCEDURE SP_MODIFICAR_MEDICO(P_RUT NUMBER,P_NOMBRE VARCHAR2, P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2, P_AMATERNO VARCHAR2,
                        P_TELEFONO NUMBER, P_SUELDO_BASE NUMBER, P_FECHA_CONTRATO DATE, P_COMISION NUMBER, P_UNI_ID NUMBER, 
                        P_CARGO_ID NUMBER, P_ESP_ID NUMBER, P_JEFE_RUT NUMBER)
IS
BEGIN
    UPDATE MEDICO SET PNOMBRE=P_NOMBRE,SNOMBRE=P_SNOMBRE,APATERNO=P_APATERNO,AMATERNO=P_AMATERNO,TELEFONO=P_TELEFONO,
    SUELDO_BASE=P_SUELDO_BASE,FECHA_CONTRATO=P_FECHA_CONTRATO,COMISION=P_COMISION,UNI_ID=P_UNI_ID,CAR_ID=P_CARGO_ID,ESP_ID=P_ESP_ID,JEFE_RUT=P_JEFE_RUT WHERE MED_RUT=P_RUT;
END;

CREATE OR REPLACE PROCEDURE SP_LISTAR_MEDICOS(P_MEDICO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_MEDICO FOR
        SELECT me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
        me.SUELDO_BASE,NVL(me.COMISION,0) AS "COMISION",
        u.NOMBRE AS "UNIDAD",ca.NOMBRE AS "CARGO",es.NOMBRE AS "ESPECIALIDAD" FROM MEDICO me
        JOIN UNIDAD u ON u.uni_id=me.uni_id
        JOIN CARGO ca ON ca.car_id=me.car_id
        JOIN ESPECIALIDAD es ON es.esp_id=me.esp_id;
END;

CREATE OR REPLACE PROCEDURE SP_ELIMINAR_MEDICO(P_RUT NUMBER)
IS
BEGIN
    DELETE FROM MEDICO WHERE MED_RUT = P_RUT;
END;

SELECT * FROM UNIDAD;

CREATE OR REPLACE PROCEDURE SP_OBTENER_DESCUENTO_3RA_EDAD(P_EDAD NUMBER, P_PORC_DESCTO OUT NUMBER)
IS
BEGIN
    SELECT PORCENTAJE_DESCTO INTO P_PORC_DESCTO FROM PORC_DESCTO_3RA_EDAD WHERE ANNO_INI<=P_EDAD AND ANNO_TER>=P_EDAD;
END;


CREATE OR REPLACE PROCEDURE SP_OBTENER_ESPECIALIDADES(P_ESPECIALIDAD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ESPECIALIDAD
    FOR
        SELECT ESP_ID,NOMBRE FROM ESPECIALDAD;
END;

CREATE OR REPLACE PROCEDURE SP_OBTENER_UNIDADES(P_UNIDAD OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_UNIDAD
    FOR
        SELECT CAR_ID,NOMBRE FROM CARGO;
END;


CREATE OR REPLACE PROCEDURE SP_LISTAR_ATENCIONES_PACIENTE(P_RUT_PAC NUMBER,P_ATENCION OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ATENCION FOR
        SELECT ate.ATE_ID,me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
                pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT PACIENTE",pa.PNOMBRE||' '||pa.APATERNO AS "NOMBRE PACIENTE",
                ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
                INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
                INNER JOIN MEDICO me ON ate.med_rut=me.med_rut
                WHERE pa.PAC_RUT=P_RUT_PAC;
END;

CREATE OR REPLACE PROCEDURE SP_LISTAR_ATENCIONES_MEDICO(P_RUT_MED NUMBER,P_ATENCION_MEDICO OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_ATENCION_MEDICO FOR
        SELECT ate.ATE_ID,me.MED_RUT||'-'||me.DV_RUT AS "RUT MEDICO",me.PNOMBRE||' '||me.APATERNO AS "NOMBRE MEDICO",
                pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT PACIENTE",pa.PNOMBRE||' '||pa.APATERNO AS "NOMBRE PACIENTE",
                ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
                INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
                INNER JOIN MEDICO me ON ate.med_rut=me.med_rut
                WHERE me.med_rut=P_RUT_MED;
END;

SELECT * FROM ATENCION ate;
SELECT * FROM PAGO_ATENCION;

SELECT ate.ATE_ID,pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE",ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
        INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut
        

SELECT ate.ATE_ID,pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE",ate.fecha_atencion AS "FECHA ATENCION",ate.hr_atencion AS "HORA ATENCION",ate.COSTO  FROM ATENCION ate
    INNER JOIN PACIENTE pa ON ate.pac_rut=pa.pac_rut;
    
SELECT * FROM ATENCION;
SELECT * FROM PAGO_ATENCION;

DECLARE 
    C_PACIENTE SYS_REFCURSOR;
    V_RUT NUMBER;
BEGIN
    LISTAR_RUT_PACIENTES(C_PACIENTE);
    LOOP 
        FETCH C_PACIENTE INTO V_RUT;
        EXIT WHEN C_PACIENTE%NOTFOUND;
        dbms_output.put_line(V_RUT);
    END LOOP;
    CLOSE C_PACIENTE;
END;

--CALCULAR EDAD DEL PACIENTE
SELECT 
    trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(fecha_nacimiento, 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) AS "FECHA NACIMIENTO"
FROM PACIENTE;

SELECT * FROM USUARIO;
SELECT * FROM PACIENTE;
SELECT * FROM SALUD;
SELECT * FROM TIPO_SALUD;
SELECT pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE", sa.descripcion FROM PACIENTE pa
INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id;
SELECT * FROM PORC_DESCTO_3RA_EDAD;

SELECT * FROM ATENCION;
SELECT TO_CHAR(SYSDATE,'HH24:MM') AS CURRENT_HOUR FROM DUAL;

--PREGUNTAR ACERCA DE LA TABLA ATENCIONES_MEDICAS_MENSUALES
--MONTO A ATENCION DE LA TABLA PAGO ATENCION
--COSTO DE LA TABLA ATENCION
--COSTO PAGO SALUD

--INSERT INTO VALUES(,,) RETURNING ID INTO V_ID;
--UPDATE
--DELETE

--******************************************NO UTILIZAR************************************
CREATE OR REPLACE PROCEDURE INGRESAR_USUARIO(P_USUARIO VARCHAR2, P_PASS VARCHAR2, P_IDTIPOUSUARIO NUMBER, P_IDUSUARIO OUT NUMBER)
IS
    V_IDUSUARIO NUMBER;
BEGIN
    V_IDUSUARIO:=SEQ_USUARIO.NEXTVAL;
    INSERT INTO USUARIO VALUES (V_IDUSUARIO,P_USUARIO,P_PASS,P_IDTIPOUSUARIO);
    P_IDUSUARIO:=V_IDUSUARIO;
END INGRESAR_USUARIO;