CREATE OR REPLACE PROCEDURE LISTAR_RUT_PACIENTES(P_PACIENTE OUT SYS_REFCURSOR)
IS
BEGIN
    OPEN P_PACIENTE
    FOR
        SELECT pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE", sa.descripcion FROM PACIENTE pa
        INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id;
END;

CREATE OR REPLACE PROCEDURE INGRESAR_USUARIO(P_USUARIO VARCHAR2, P_PASS VARCHAR2, P_IDTIPOUSUARIO NUMBER, P_IDUSUARIO OUT NUMBER)
IS
    V_IDUSUARIO NUMBER;
BEGIN
    V_IDUSUARIO:=SEQ_USUARIO.NEXTVAL;
    INSERT INTO USUARIO VALUES (V_IDUSUARIO,P_USUARIO,P_PASS,P_IDTIPOUSUARIO);
    P_IDUSUARIO:=V_IDUSUARIO;
END INGRESAR_USUARIO;

CREATE OR REPLACE PROCEDURE INGRESAR_PACIENTE(P_RUT IN OUT NUMBER,P_DV_RUT VARCHAR2, P_NOMBRE VARCHAR2,
    P_SNOMBRE VARCHAR2,P_APATERNO VARCHAR2,P_AMATERNO VARCHAR2,P_FECNACIMIENTO DATE,P_TELEFONO VARCHAR2,P_SALUD_ID NUMBER, P_IDUSUARIO NUMBER)
IS
    V_IDPACIENTE NUMBER;
BEGIN
    INSERT INTO PACIENTE VALUES(P_RUT,P_DV_RUT, P_NOMBRE,P_SNOMBRE,P_APATERNO,P_AMATERNO,P_FECNACIMIENTO,P_TELEFONO,P_SALUD_ID, P_IDUSUARIO);
END INGRESAR_PACIENTE;

CREATE OR REPLACE PROCEDURE INGRESAR_ATENCION(P_FEC_ATENCION DATE, P_HORA_ATENCION VARCHAR2, P_COSTO NUMBER,
                                                P_MED_RUT NUMBER, P_PAC_RUT NUMBER, P_IDATENCION OUT NUMBER)
IS
    V_IDATENCION NUMBER;
BEGIN
    V_IDATENCION:=SEQ_ATENCION.NEXTVAL;
    INSERT INTO ATENCION VALUES(V_IDATENCION,P_FEC_ATENCION,P_HORA_ATENCION,P_COSTO,P_MED_RUT,P_PAC_RUT);
    P_IDATENCION:=V_IDATENCION;
END;

CREATE OR REPLACE PROCEDURE INGRESAR_PAGO_ATENCION(P_IDATENCION NUMBER, P_FEC_VENC_PAGO DATE, P_FEC_PAGO DATE, P_MONTO_ATENCION NUMBER, P_MONTO_CANCELAR NUMBER, P_OBS_PAGO VARCHAR2)
IS
BEGIN
    INSERT INTO PAGO_ATENCION VALUES(P_IDATENCION,P_FEC_VENC_PAGO,P_FEC_PAGO, P_MONTO_ATENCION,P_MONTO_CANCELAR,P_OBS_PAGO);
END;

CREATE OR REPLACE PROCEDURE LISTAR_ATENCIONES_MEDICO(P_MED_RUT NUMBER,P_PAC_RUT NUMBER)
IS
BEGIN
    SELECT pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE",FECHA Y HORA,ate.COSTO FROM ATENCION ate
    INNER JOIN PACIENTE pa ON ate.pac_rut=p_pac_rut;
END;

SELECT * FROM ATENCION;
SELECT * FROM PAGO_ATENCION;

DECLARE 
    C_PACIENTE SYS_REFCURSOR;
    V_RUT NUMBER;
BEGIN
    LISTAR_RUT_PACIENTES(C_PACIENTE);
    LOOP 
        FETCH C_PACIENTE INTO V_RUT;
        EXIT WHEN C_PACIENTE%NOTFOUND;
        dbms_output.put_line(V_RUT);
    END LOOP;
    CLOSE C_PACIENTE;
END;


PROCEDURE OBTENER_DESCUENTO_3RA_EDAD(P_EDAD NUMBER, P_PORC_DESCTO OUT NUMBER)
IS
BEGIN
    SELECT PORCENTAJE_DESCTO INTO P_PORC_DESCTO FROM PORC_DESCTO_3RA_EDAD WHERE ANNO_INI<=P_EDAD AND ANNO_TER>=P_EDAD;
END;

PROCEDURE 


--CALCULAR EDAD DEL PACIENTE
SELECT 
    trunc(months_between(to_date(to_char(SYSDATE, 'dd/mm/yyyy'), 'dd/mm/yyyy'), to_date(to_char(fecha_nacimiento, 'dd/mm/yyyy'), 'dd/mm/yyyy'))/12) AS "FECHA NACIMIENTO"
FROM PACIENTE;

SELECT * FROM USUARIO;
SELECT * FROM PACIENTE;
SELECT pa.PAC_RUT||'-'||pa.DV_RUT AS "RUT",pa.PNOMBRE||' '||pa.APATERNO||' '||pa.AMATERNO AS "NOMBRE", sa.descripcion FROM PACIENTE pa
INNER JOIN SALUD sa ON pa.sal_id=sa.sal_id;
SELECT * FROM PORC_DESCTO_3RA_EDAD;

--PREGUNTAR ACERCA DE LA TABLA ATENCIONES_MEDICAS_MENSUALES
--MONTO A ATENCION DE LA TABLA PAGO ATENCION
--COSTO DE LA TABLA ATENCION
--COSTO PAGO SALUD

--INSERT INTO VALUES(,,) RETURNING ID INTO V_ID;
--UPDATE
--DELETE